test-job1:
  stage: test
  image: ubuntu:latest
  script:
    - echo "This job tests something"
    # GitLab automatically checks out the repository.
    - echo "Installing az CLI"
    - apt-get update
    - apt-get install azure-cli
    - echo "Installing jq"
    - apt-get install -y jq
    - echo "Installing Python 3.11"
    - apt-get install -y python3.11
    - echo "Installing pip"
    - apt-get install -y python3-pip
    - echo "Installing Azure CLI extensions"
    - echo "Installing az ml extension..."
    - az extension add -n ml -y
    - echo "Performing Azure login"
    # Write the JSON credentials (assumed to be stored in an environment variable named AZURE_CREDENTIALS)
    - echo "$AZURE_CREDENTIALS" > azure_creds.json
    # Use jq to extract values; ensure jq is installed on the runner; alternatively, adjust the command as needed.
    - az login --service-principal --username $(jq -r '.clientId' azure_creds.json) --password $(jq -r '.clientSecret' azure_creds.json) --tenant $(jq -r '.tenantId' azure_creds.json)
    - echo "Listing current directory"
    - ls
    - echo "Installing ai foundry dependencies"
    - pip3.11 install -r requirements.txt
    - echo "Running AI Foundry evaluations"
    - python3.11 src/evaluation.py
  