test-job1:
  stage: test
  image: mcr.microsoft.com/azure-cli
  before_script: 
    - echo AZURE_OPENAI_GPT_MODEL_NAME=$AZURE_OPENAI_GPT_MODEL_NAME >> .env         
    - echo AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT >> .env 
    - apt-get update && apt-get install -y python3.11 python3.11-pip
    - pip install azure-identity azure-ai-projects promptflow azure-ai-evaluation
  script:
    - echo "This job tests something"
    - echo "Installing Azure CLI extensions"
    - echo "Installing az ml extension..."
    - echo "Listing current directory"
    - ls
    - echo "Running evaluation"
    - pf run create -f src/evaluation_flow/run.yml --stream
   