default:
  image: mcr.microsoft.com/azure-cli:latest

auth:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  script:
    - az login --tenant $AZURE_TENANT
    - az account show
    - az extension add -n ml -y

test-job1:
  stage: test
  image: python:3.11-slim
  before_script: 
    - echo AZURE_OPENAI_GPT_MODEL_NAME=$AZURE_OPENAI_GPT_MODEL_NAME >> .env         
    - echo AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT >> .env 
    - apt-get update
    - apt-get install -y python3.11
  script:
    - echo "This job tests something"
    - echo "Installing Azure CLI extensions"
    - echo "Installing az ml extension..."
    - echo "Listing current directory"
    - ls
    - echo "Installing ai foundry dependencies"
    - pip install -r requirements.txt
    - echo "Running AI Foundry evaluations"
    - python src/evaluation.py
  