test-job1:
  stage: test
  image: python:3.11-slim
  before_script: 
    - echo AZURE_OPENAI_GPT_MODEL_NAME=$AZURE_OPENAI_GPT_MODEL_NAME >> .env         
    - echo AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT >> .env 
    - pip install azure-identity azure-ai-projects promptflow
  script:
    - echo "This job tests something"
    - echo "Installing Azure CLI extensions"
    - echo "Installing az ml extension..."
    - echo "Listing current directory"
    - ls
    - echo "Running evaluation"
    - pf run create --flow src/evaluation_flow/run.yml --stream
   