test-job1:
  stage: test
  image: mcr.microsoft.com/azure-cli
  script:
    - echo "This job tests something"
    # GitLab automatically checks out the repository.
    - echo "Installing Azure CLI extensions"
    - echo "Installing az ml extension..."
    - az extension add -n ml -y
    - echo "Performing Azure login"
    - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT
    - echo "Listing current directory"
    - ls
    - echo "Installing ai foundry dependencies"
    - pip install -r requirements.txt
    - echo "Running AI Foundry evaluations"
    - python src/evaluation.py
  