test-job1:
  stage: test
  image: mcr.microsoft.com/azure-cli
  before_script: 
    - echo AZURE_OPENAI_GPT_MODEL_NAME=$AZURE_OPENAI_GPT_MODEL_NAME >> .env         
    - echo AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT >> .env 
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install azure-identity azure-ai-projects promptflow azure-ai-evaluation
    - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT
  script:
    - echo "This job tests something"
    - echo "Installing az ml extension..."
    - echo "Listing current directory"
    - ls
    - echo "Running evaluation"
    - pf run create -f src/evaluation_flow/run.yml --stream
   